# Generated by Django 3.1.5 on 2021-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subscription_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='position',
            field=models.CharField(default='Doutorado', max_length=150, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
