# Generated by Django 3.1.5 on 2021-07-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_subscription_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='module_interest',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LIneA Science Server'), (2, 'Jupyter Notebook')], default=1, verbose_name='Module Interest'),
            preserve_default=False,
        ),
    ]
