# Generated by Django 3.1.5 on 2021-07-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_subscription_module_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='module_interest',
            field=models.CharField(choices=[('1', 'LIneA Science Server'), ('2', 'Jupyter Notebook'), ('1,2', 'LIneA Science Server & Jupyter Notebook')], max_length=150, verbose_name='Module Interest'),
        ),
    ]
