# Generated by Django 3.1.5 on 2021-07-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210716_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='education',
        ),
    ]
